pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/RamyaAgali/smarttrip-ai-travel-planner'
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dir('backend/auth-service/authservice/authservice') {
                        bat 'mvn clean test'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('backend/auth-service/authservice/authservice') {
                        bat 'docker build -t auth-service-image:latest .'
                        bat "docker tag auth-service-image:latest ramya6367/auth-service:latest"
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                bat """
                echo %DOCKERHUB_CREDENTIALS_PSW% | docker login -u %DOCKERHUB_CREDENTIALS_USR% --password-stdin
                docker push ramya6367/auth-service:latest
                """
            }
        }

        stage('Stop Old Container') {
            steps {
                script {
                    bat '''
                    docker ps -a -q -f name=auth-service > cid.txt
                    set CID=
                    for /f "tokens=*" %%i in (cid.txt) do set CID=%%i
                    if NOT "%CID%"=="" docker rm -f %CID%
                    '''
                }
            }
        }

        stage('Run New Container') {
            steps {
                script {
                    bat '''
                    docker run -d ^
                        --name auth-service ^
                        -p 8081:8081 ^
                        ramya6367/auth-service:latest
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Auth Service CI/CD Successful'
        }
        failure {
            echo 'Auth Service CI/CD Failed'
        }
    }
}