pipeline {
    agent any

    tools {
        maven "Maven3"
        jdk "JDK17"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn -f backend/auth-service/authservice/authservice/pom.xml clean install -DskipTests=false'
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                docker build -t auth-service-image:latest backend/auth-service/
                '''
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'backend/auth-service/authservice/authservice/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Auth Service CI Completed Successfully.'
        }
        failure {
            echo 'Auth Service CI Failed.'
        }
    }
}