pipeline {
    agent any

    environment {
        SONAR_AUTH_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/RamyaAgali/smarttrip-ai-travel-planner'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('local-sonar') {
                    bat """
                        mvn sonar:sonar ^
                        -Dsonar.projectKey=auth-service ^
                        -Dsonar.host.url=http://localhost:9000 ^
                        -Dsonar.login=%SONAR_AUTH_TOKEN%
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('backend/auth-service/authservice/authservice') {
                        bat 'docker build -t auth-service-image:latest .'
                    }
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                script {
                    bat """
                        docker ps -a -q -f name=auth-service > cid.txt
                        set CID=
                        for /f "tokens=*" %%i in (cid.txt) do set CID=%%i
                        if NOT "%CID%"=="" docker rm -f %CID%
                    """
                }
            }
        }

        stage('Run New Container') {
            steps {
                bat """
                    docker run -d ^
                        --name auth-service ^
                        -p 8081:8081 ^
                        auth-service-image:latest
                """
            }
        }
    }

    post {
        success {
            echo 'Auth Service Pipeline Success'
        }
        failure {
            echo 'Auth Service Pipeline Failed'
        }
    }
}