pipeline {
    agent any

    tools {
        maven "Maven-3.9"
        jdk "JDK17"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn -f backend/trip-service/tripservice/tripservice/pom.xml clean install -DskipTests=false'
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                docker build -t trip-service-image:latest backend/trip-service/
                '''
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'backend/trip-service/tripservice/tripservice/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Trip Service CI Completed Successfully.'
        }
        failure {
            echo 'Trip Service CI Failed.'
        }
    }
}