pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/RamyaAgali/smarttrip-ai-travel-planner'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    cd backend/trip-service/tripservice/tripservice
                    docker build -t trip-service-image:latest .
                    """
                }
            }
        }

        stage('Run Container for Testing') {
            steps {
                script {
                    sh """
                    docker rm -f travel-service-test || true
                    docker run -d --name travel-service-test -p 8082:8080 travel-service-image:latest
                    """
                }
            }
        }

        stage('Publish Image') {
            steps {
                echo "Push to Docker Hub or deploy server (optional)"
            }
        }
    }
}